### ISSUE TITLE
Error Code On Launch

### ISSUE THREAD

**Issue by 2kAmbitions** [Orbmu2k/nvidiaProfileInspector#153]
Error
The type intializer for 'nspector.Common.DrsServiceLocator' threw an exception.

at nspector.frmDrvSettings..ctor(Boolean showCsnOnly, Boolean skipScan)
at nspector.Program.Main(String[] args)

Any help is appreciated thank you!

**Comment by Dylanlegros8** [comment]
its doing it to me to

**Comment by Stephanov2077** [comment]
Same here!

**Comment by susmoro** [comment]
> Errore L'inizializzatore del tipo per 'nspector.Common.DrsServiceLocator' ha generato un'eccezione.
> 
> in nspector.frmDrvSettings..ctor(Boolean showCsnOnly, Boolean skipScan) in nspector.Program.Main(String[] args)
> 
> Ogni aiuto è apprezzato, grazie!

I also get the same error, please help us

**Comment by Fr4nc1ssss** [comment]
me too, can somone say of to fix it?
