### ISSUE TITLE
The type intializer for 'nspector.Common.DrsServiceLocator' threw an exception.

### ISSUE THREAD

**Issue by Stephanov2077** [Orbmu2k/nvidiaProfileInspector#158]
Help please the app doesnt open anymore.
Win11, rtx 3090, 536.99 WHQL drivers, 16gb ram, i5 12400f.

The type intializer for 'nspector.Common.DrsServiceLocator' threw an exception.

at nspector.frmDrvSettings..ctor(Boolean showCsnOnly, Boolean skipScan)
at nspector.Program.Main(String[] args)

**Comment by Stephanov2077** [comment]
...

**Comment by Stephanov2077** [comment]
Already fixed, I installed the new driver 537.13 and now NviDIa Porfile Inspector is working for me.

**Comment by Stephanov2077** [comment]
Already fixed, I installed the new driver 537.13 and now NviDIa Porfile Inspector is working for me.
