### ISSUE TITLE
The type intializer for 'nspector.Common.DrsServiceLocator' threw an exception.

### ISSUE THREAD

**Issue by Galjak1** [Orbmu2k/nvidiaProfileInspector#167]
Error
The type intializer for 'nspector.Common.DrsServiceLocator' threw an exception.

at nspector.frmDrvSettings..ctor(Boolean showCsnOnly, Boolean skipScan)
at nspector.Program.Main(String[] args)

can i even run this if i am using intel graphic card, and is there profile inspector for intel?

**Comment by sanyfc** [comment]
i cant open nvidia profile inspector on codelifes video on the boosting the fps and it doesnt let me open it

**Comment by GhostyXV** [comment]
It should work on intel. On one of my laptops with an intel graphics card, it works perfectly fine. The one im currently using seems to not work, which has an intel chip aswell. It might be a driver issue, but im not entirely sure

**Comment by AnubyteCode** [comment]
Usually a .xml error. Try Notepad++, XML Tools plugin, set it to autocheck syntax.

**Comment by Skillissuegetbetter** [comment]
> Usually a .xml error. Try Notepad++, XML Tools plugin, set it to autocheck syntax.

Can you explain this more thorughly sorry but im not too smart

**Comment by AnubyteCode** [comment]
If there is a problem with the formatting of the reference.xml, that error happens.
