### ISSUE TITLE
Won't even run

### ISSUE THREAD

**Issue by YomamaNow** [Orbmu2k/nvidiaProfileInspector#220]
The type initializer for 'nspector.Common.DrsServiceLocator' threw an exception.

   at nspector.frmDrvSettings..ctor(Boolean showCsnOnly, Boolean skipScan)
   at nspector.Program.Main(String[] args)

**Comment by YomamaNow** [comment]
Reference this thread, because it was accidentally closed without ever being solved: https://github.com/Orbmu2k/nvidiaProfileInspector/issues/132

I"m using 2.4.0.4

**Comment by Alkapivo** [comment]
I have the same issue ('nspector.Common.DrsServiceLocator'), I wanted to use nvidiaprofileinspector, because after last update my notebook 1650 stop working. Is your nvidia gpu available in task manager? Can you open nvidia control panel?

**Comment by Gary9** [comment]
> The type initializer for 'nspector.Common.DrsServiceLocator' threw an exception.
> 
> at nspector.frmDrvSettings..ctor(Boolean showCsnOnly, Boolean skipScan) at nspector.Program.Main(String[] args)

You dont mention when you get the exception, if it is when you try to run the exe file  then I had the same problem.   Copy the whole uncompressed folder to Program Files or Program Files(86) and try opening it from there as that worked for me.

**Comment by bor888** [comment]
There is a workaround.
Go to: C:\ProgramData\NVIDIA Corporation\
delete or rename "Drs" folder to "Drs.bak"
create new "Drs" folder.

**Comment by bor888** [comment]
One more thing
You have to edit security settings on new folder
Find your username and allow FULL permissions for "This folder, subfolders and files"

**Comment by fragk1ass** [comment]
> There is a workaround. Go to: C:\ProgramData\NVIDIA Corporation delete or rename "Drs" folder to "Drs.bak" create new "Drs" folder.

Man It does not work. Can you help us more

**Comment by bor888** [comment]
Then that means that your driver installation is corrupted.
You have to uninstall drivers from Control Panel and use Display Driver Uninstaller in safe mode,
and then install the latest driver from Nvidia.
